### PR TITLE
Fix on-premise API bugs

### PR DESCRIPTION
**Pull request by plamendelchev**
The following PR fixes two bugs I encountered while using the plugin with an on-premise JIRA instance.

I have tested the changes and can confirm that the plugin works as intended with them.

### CODE REVIEW

**Review by adyscorpius — APPROVED** [review]
Looks good. Nice catch on the apiVersion not being used on the URL.

**Comment by adyscorpius** [comment]
Hi.. I'm looking back at the original commit by @nightscape .

Is this something that is an alternative way to access on-premise API? There seems to be two types of authentication flows (Personal access tokens and Bearer auth). Is that accurate?

**Comment by plamendelchev** [comment]
Hi, yes you are correct. The on-promise API can be accessed both with OAuth and Basic Authentication:
https://developer.atlassian.com/server/jira/platform/security-overview/
I personally use Basic Authentication, but I did not take into account that OAuth is also a valid option, so maybe my changes have not addressed the issue fully.

**Comment by adyscorpius** [comment]
Just went through the documentations again and funnily Basic and Bearer both work in the cloud, so there's no way of testing this stuff really. 

But I've made it highly configurable now. Hopefully this new version solves for both PAT and Basic Authentication use cases. I don't think supporting OAuth makes much sense with PAT. 

Happy if you all can test it out. Release v0.3.0 now.

**Pull request merged**
